//dependencyResolutionManagement {
//    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
//    repositories {
//        google()
//        mavenCentral()
//        mavenLocal()
//        maven {
//            url = uri("https://plugins.gradle.org/m2/")
//        }
//    }
//}
rootProject.name = "CodeBase"
if (PUBLISH == "false") {
    include ':app'
}
include ':plugin'
include ':library'
include ':plugin-app'
//include ':test'
