plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'codebase-plugin'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 33

    defaultConfig {
        applicationId "com.cleo.codebase"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
//        useIR = true
    }
    buildFeatures {
        compose true
        viewBinding true
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_version
        kotlinCompilerVersion kotlin_version
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

codeConfig {

}

//def artifactType = Attribute.of('artifactType', String)
//def minified = Attribute.of('minified', Boolean)
//def keepPatterns = [
//        "guava": [
//                "com.google.common.base.Optional",
//                "com.google.common.base.AbstractIterator"
//        ] as Set
//]
dependencies {
//    registerTransform(com.cleo.codebase.plugin.transform.Unzip) {
//        from.attribute(artifactType, 'jar')
//        to.attribute(artifactType, 'java-classes-directory')
//    }
//
//    registerTransform(com.cleo.codebase.plugin.transform.Minify) {
//        from.attribute(minified, false).attribute(artifactType, "jar")
//        to.attribute(minified, true).attribute(artifactType, "jar")
//
//        parameters {
//            keepClassesByArtifact = keepPatterns
//        }
//    }

    implementation ("com.github.bumptech.glide:glide:4.14.2") {
        exclude group: "com.android.support"
    }
    implementation 'androidx.webkit:webkit:1.6.0'
    kapt 'com.github.bumptech.glide:compiler:4.14.2'

    implementation project(':library')
    implementation "org.ow2.asm:asm:$ASM_VERSION"
    implementation "org.ow2.asm:asm-tree:$ASM_VERSION"
    implementation "org.ow2.asm:asm-util:$ASM_VERSION"
    implementation "org.ow2.asm:asm-analysis:$ASM_VERSION"
    implementation "org.ow2.asm:asm-commons:$ASM_VERSION"

    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation "androidx.core:core-ktx:$core_ktx"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle"
    implementation "androidx.navigation:navigation-fragment-ktx:$navigation"
    implementation "androidx.navigation:navigation-ui-ktx:$navigation"
    implementation "androidx.fragment:fragment-ktx:$fragment_ktx"
    implementation "androidx.appcompat:appcompat:$appcompat"
    implementation "androidx.constraintlayout:constraintlayout:$constraintlayout"
    implementation "androidx.work:work-runtime-ktx:$work_version"
    implementation "androidx.work:work-rxjava2:$work_version"
    implementation "androidx.work:work-multiprocess:$work_version"
    implementation "com.google.android.material:material:$material"
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation "androidx.activity:activity-compose:$activity_compose"
    implementation "androidx.annotation:annotation:$annotation"
    implementation "androidx.slice:slice-builders:$slice"
    implementation "androidx.slice:slice-core:$slice"
    testImplementation "junit:junit:$junit"
    androidTestImplementation "androidx.work:work-testing:$work_version"
    androidTestImplementation "androidx.test.ext:junit:$androidx_junit"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espresso"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"
}